import { marker } from '@colsen1991/ngx-translate-extract-marker';
import { Marker, Skin } from '../../@shared/model/app.types';
import { DeckChrome } from './deck.catalog';
import { AppModule } from './deck.types';

export const DECK_CHROME_LABELS: Record<Skin, DeckChrome> = {
  cyberpunk: {
    grid: marker('deck.cyberpunk.chrome.grid'),
    'grid-value': marker('deck.cyberpunk.chrome.grid-value'),
    noise: marker('deck.cyberpunk.chrome.noise'),
    signal: marker('deck.cyberpunk.chrome.signal'),
    'signal-value': marker('deck.cyberpunk.chrome.signal-value'),
    kicker: marker('deck.cyberpunk.chrome.kicker'),
    res: marker('deck.cyberpunk.chrome.res'),
    firewall: marker('deck.cyberpunk.chrome.firewall'),
    'firewall-value': marker('deck.cyberpunk.chrome.firewall-value'),
    'programs-loaded': marker('deck.cyberpunk.chrome.programs-loaded'),
    nuyen: marker('deck.cyberpunk.chrome.nuyen'),
    trace: marker('deck.cyberpunk.chrome.trace'),
    'trace-value': marker('deck.cyberpunk.chrome.trace-value'),
    ice: marker('deck.cyberpunk.chrome.ice'),
    'ice-value': marker('deck.cyberpunk.chrome.ice-value'),
    uptime: marker('deck.cyberpunk.chrome.uptime'),
    'node-online': marker('deck.cyberpunk.chrome.node-online'),
    'node-standby': marker('deck.cyberpunk.chrome.node-standby'),
    'node-offline': marker('deck.cyberpunk.chrome.node-offline'),
    'empty-title': marker('deck.cyberpunk.chrome.empty-title'),
    'empty-body': marker('deck.cyberpunk.chrome.empty-body'),
    'empty-action': marker('deck.cyberpunk.chrome.empty-action'),
  },
  boomer: {
    grid: marker('deck.boomer.chrome.grid'),
    'grid-value': marker('deck.boomer.chrome.grid-value'),
    noise: marker('deck.boomer.chrome.noise'),
    signal: marker('deck.boomer.chrome.signal'),
    'signal-value': marker('deck.boomer.chrome.signal-value'),
    kicker: marker('deck.boomer.chrome.kicker'),
    res: marker('deck.boomer.chrome.res'),
    firewall: marker('deck.boomer.chrome.firewall'),
    'firewall-value': marker('deck.boomer.chrome.firewall-value'),
    'programs-loaded': marker('deck.boomer.chrome.programs-loaded'),
    nuyen: marker('deck.boomer.chrome.nuyen'),
    trace: marker('deck.boomer.chrome.trace'),
    'trace-value': marker('deck.boomer.chrome.trace-value'),
    ice: marker('deck.boomer.chrome.ice'),
    'ice-value': marker('deck.boomer.chrome.ice-value'),
    uptime: marker('deck.boomer.chrome.uptime'),
    'node-online': marker('deck.boomer.chrome.node-online'),
    'node-standby': marker('deck.boomer.chrome.node-standby'),
    'node-offline': marker('deck.boomer.chrome.node-offline'),
    'empty-title': marker('deck.boomer.chrome.empty-title'),
    'empty-body': marker('deck.boomer.chrome.empty-body'),
    'empty-action': marker('deck.boomer.chrome.empty-action'),
  },
};

export const DECK_MODULE_LABELS: Record<AppModule, Marker> = {
  commlink: marker('deck.module.commlink'),
  tracking: marker('deck.module.tracking'),
  'office-time': marker('deck.module.office-time'),
  notifications: marker('deck.module.notifications'),
  notes: marker('deck.module.notes'),
  household: marker('deck.module.household'),
  tasks: marker('deck.module.tasks'),
  cash: marker('deck.module.cash'),
  trackplay: marker('deck.module.trackplay'),
  ritual: marker('deck.module.ritual'),
  geist: marker('deck.module.geist'),
  vitals: marker('deck.module.vitals'),
  handbook: marker('deck.module.handbook'),
  settings: marker('deck.module.settings'),
};
