import {
  bookOutline,
  businessOutline,
  cartOutline,
  checkboxOutline,
  diceOutline,
  discOutline,
  documentsOutline,
  documentTextOutline,
  fileTrayStackedOutline,
  gridOutline,
  hardwareChipOutline,
  layersOutline,
  libraryOutline,
  notificationsOutline,
  optionsOutline,
  pricetagsOutline,
  pulseOutline,
  receiptOutline,
  restaurantOutline,
  settingsOutline,
  sparklesOutline,
  speedometerOutline,
  sunnyOutline,
  timerOutline,
  walletOutline,
} from 'ionicons/icons';

export const DECK_ICONS = {
  'book-outline': bookOutline,
  'business-outline': businessOutline,
  'cart-outline': cartOutline,
  'checkbox-outline': checkboxOutline,
  'dice-outline': diceOutline,
  'disc-outline': discOutline,
  'documents-outline': documentsOutline,
  'document-text-outline': documentTextOutline,
  'file-tray-stacked-outline': fileTrayStackedOutline,
  'grid-outline': gridOutline,
  'hardware-chip-outline': hardwareChipOutline,
  'layers-outline': layersOutline,
  'library-outline': libraryOutline,
  'notifications-outline': notificationsOutline,
  'options-outline': optionsOutline,
  'pricetags-outline': pricetagsOutline,
  'pulse-outline': pulseOutline,
  'receipt-outline': receiptOutline,
  'restaurant-outline': restaurantOutline,
  'settings-outline': settingsOutline,
  'sparkles-outline': sparklesOutline,
  'speedometer-outline': speedometerOutline,
  'sunny-outline': sunnyOutline,
  'timer-outline': timerOutline,
  'wallet-outline': walletOutline,
} as const;

export type DeckIcon = keyof typeof DECK_ICONS;
